# path or URL to sample sheet (TSV format, columns: sample, condition, ...)
samples: config/samples.tsv
# path or URL to sequencing unit sheet (TSV format, columns: sample, unit, fq1, fq2)
# Units are technical replicates (e.g. lanes, or resequencing of the same biological
# sample).
units: config/units.tsv


ref:
  #Ensembl species name
  species: homo_sapiens
  # Ensembl release (make sure to take one where snpeff data is available, check 'snpEff databases' output)
  release: 104
  # Genome build
  build: GRCh38

trimming:
  activate: true

mergeReads:
  activate: false

pca:
  activate: True
  labels:
    # columns of sample sheet to use for PCA
    - condition

diffexp:
  # contrasts for the deseq2 results method
  contrasts:
    unknown1-vs-unknown2:
      - unknown1
      - unknown2
  model: ~condition

params:
  cutadapt-pe: 
    "--minimum-length 35 -a AGAGCACACGTCTGAACTCCAGTCAC -g AGATCGGAAGAGCACACGT -A AGAGCACACGTCTGAACTCCAGTCAC -G AGATCGGAAGAGCACACGT"
  cutadapt-se: ""
  star: "--twopassMode Basic --twopass1readsN -1 --sjdbOverhang 149 --sjdbGTFtagExonParentGene gene_name --outSAMtype BAM Unsorted --quantMode GeneCounts --outFilterMultimapNmax 200 --limitSjdbInsertNsj 10000000"
